export const SERVER_API_URL = 'https://api.mercadolibre.com'
export const SEARCH_ENDPOINT = 'sites/MLA/search'
export const ITEM_ENDPOINT = 'items/'
export const ITEM_DESCRIPTION_ENDPOINT = 'description'
export const CATEGORIES_ENDPOINT = 'categories/'
